name: Docker CI/CD Build and Push

# 1. Quando rodar (Triggers)
on:
  push:
    branches: [ "main" ]

# 2. Sequência de Tarefas (Jobs)
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 2.1 Checkout: Baixa o código do seu repositório
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2.2 Login: Faz o login no Docker Hub usando os segredos
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # 2.3 Set up Buildx (Otimizador de Build, resolve o aviso 'DEPRECATED')
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # 2.4 Build and Push: Constrói a imagem e envia para o Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/status-checker-app:latest